name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with: 
        repository: 'HariPrasath07/github-actions-lab1-q1'
        ref: 'main'
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11   

    - name: Install dependencies
      run: |
        chmod +x requirements.txt
        pip install -r requirements.txt
